default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys', '--indent', '4', '--no-ensure-ascii']
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-yapf.git
    rev: v0.30.0
    hooks:
      - id: yapf
        args: ['-i', '-vv']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.21.0
    hooks:
      - id: yamllint
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety.git
    rev: v1.1.0
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/PyCQA/bandit.git
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ['-c', '.bandit']
  - repo: https://github.com/PyCQA/pylint.git
    rev: pylint-2.4.4
    hooks:
      - id: pylint
